### ISSUE TITLE
Someone a volé mon armure en fer !!!!!!

### ISSUE THREAD

**Issue by Funeoz** [efrei-craft/ECATUP#29]
Un NERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERDNERD s'est amusé à voler mon stuff dans mon coffre dans le vanilla. 🤓

**Steps to reproduce**

1. Se faire voler son stuff

![image](https://user-images.githubusercontent.com/31157012/200265103-6ee71cc2-f4d5-44ae-8bf4-830e4fe7381f.png)
![image](https://user-images.githubusercontent.com/31157012/200265138-22654118-5908-4b60-b75f-e90a0483d264.png)
![image](https://user-images.githubusercontent.com/31157012/200265181-5b2bd93c-60a2-4aeb-8aa4-4dfa766ccda5.png)

**Comment by AstrantVdev** [comment]
c pas moi

**Comment by DocSystem** [comment]
Mdr vous vous foutez de qui xD

**Comment by Funeoz** [comment]
Quelle est cette dictature ? C'est indécent.

**Comment by gtedavid** [comment]
> Quelle est cette dictature ? C'est indécent.

C'est la procédure suivit pour abus de spam je crois...

**Comment by gtedavid** [comment]
@Funeoz c'est la procédure suivi pour abus de spam ou issue inutile je crois 
Mais je suis pas modérateur donc 🤷‍♂️

**Comment by Niilyx** [comment]
On vit vraiment dans une société. Comme si les admins n'avaient pas le droit d'ouvrir des issues. #prayfortheo

**Comment by Niilyx** [comment]
![image](https://user-images.githubusercontent.com/43385037/200276544-ac7dbb2c-f86a-45ca-92b8-f2700d172060.png)
Je te rendrai justice, @Funeoz

**Comment by Funeoz** [comment]
Enfin un développeur sérieux 💯👌👍
